### ISSUE TITLE
published nativescript-ripple 4.0.2 seems incorrect

### ISSUE THREAD

**Issue by jcassidyav** [edusperoni/nativescript-plugins#2]
It seems that nativescript-ripple was published as nativescript-ripple 4.0.2 not @edusperoni/nativescript-ripple but then the angular piece is expecting @edusperoni/nativescript-ripple.

**Comment by edusperoni** [comment]
Oops, my bad, I'll republish it

**Comment by jcassidyav** [comment]
Cheers! All Good with 4.0.3
